# Generated by Django 4.1.5 on 2023-01-07 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated_at')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Көлік')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Нөмірі')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ('uuid',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated_at')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Қала')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Citys',
                'ordering': ('uuid',),
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='Есімі')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ата-тегі')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='people.car', verbose_name='Көліктер')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='people.city', verbose_name='Қалалар')),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': 'Names',
                'ordering': ('uuid',),
            },
        ),
    ]
